Attribute Information:

The original dataset from the reference consists of 5 different folders, each with 100 files, with each file representing a single subject/person. Each file is a recording of brain activity for 23.6 seconds. The corresponding time-series is sampled into 4097 data points. Each data point is the value of the EEG recording at a different point in time. So we have total 500 individuals with each has 4097 data points for 23.5 seconds.

We divided and shuffled every 4097 data points into 23 chunks, each chunk contains 178 data points for 1 second, and each data point is the value of the EEG recording at a different point in time. So now we have 23 x 500 = 11500 pieces of information(row), each information contains 178 data points for 1 second(column), the last column represents the label y {1,2,3,4,5}. 

The response variable is y in column 179, the Explanatory variables X1, X2, ..., X178 

y contains the category of the 178-dimensional input vector. Specifically y in {1, 2, 3, 4, 5}: 

5 - eyes open, means when they were recording the EEG signal of the brain the patient had their eyes open 

4 - eyes closed, means when they were recording the EEG signal the patient had their eyes closed 

3 - Yes they identify where the region of the tumor was in the brain and recording the EEG activity from the healthy brain area 

2 - They recorder the EEG from the area where the tumor was located 

1 - Recording of seizure activity 

All subjects falling in classes 2, 3, 4, and 5 are subjects who did not have epileptic seizure. Only subjects in class 1 have epileptic seizure. Our motivation for creating this version of the data was to simplify access to the data via the creation of a .csv version of it. Although there are 5 classes most authors have done binary classification, namely class 1 (Epileptic seizure) against the rest.


Acknowledgemeant:

    UCI for providing this dataset.
    
Inspiration:

   Mr.Suresh Jois , my mentor
    
   Jeff Hammerbacher - "The best minds of my generation are thinking about how to make people click ads" 

In [83]:
#importing numpy and pandas
import numpy as np
import pandas as pd

#importing for visualization
import matplotlib.pyplot as plt

%matplotlib inline

r_s=123456

In [84]:
#importing dataset
df = pd.read_csv('G:/data/dataset/epilepsy/data.csv')

# Analysis

In [85]:
df.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]

In [86]:
df.shape

(11500, 180)

In [87]:
#Structural analysis
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Columns: 180 entries, Unnamed: 0 to y
dtypes: int64(179), object(1)
memory usage: 15.8+ MB


In [88]:
#statistical analysis
df.describe()

X1            X2            X3            X4            X5  \
count  11500.000000  11500.000000  11500.000000  11500.000000  11500.000000   
mean     -11.581391    -10.911565    -10.187130     -9.143043     -8.009739   
std      165.626284    166.059609    163.524317    161.269041    160.998007   
min    -1839.000000  -1838.000000  -1835.000000  -1845.000000  -1791.000000   
25%      -54.000000    -55.000000    -54.000000    -54.000000    -54.000000   
50%       -8.000000     -8.000000     -7.000000     -8.000000     -8.000000   
75%       34.000000     35.000000     36.000000     36.000000     35.000000   
max     1726.000000   1713.000000   1697.000000   1612.000000   1518.000000   

                 X6            X7           X8           X9           X10  \
count  11500.000000  11500.000000  11500.00000  11500.00000  11500.000000   
mean      -7.003478     -6.502087     -6.68713     -6.55800     -6.168435   
std      161.328725    161.467837    162.11912    162.03336    160.436352   
min    -1757.000000  -1832.000000  -1778.00000  -1840.00000  -1867.000000   
25%      -54.000000    -54.000000    -55.00000    -55.00000    -54.000000   
50%       -8.000000     -8.000000     -8.00000     -7.00000     -7.000000   
75%       36.000000     35.000000     36.00000     36.00000     35.250000   
max     1816.000000   2047.000000   2047.00000   2047.00000   2047.000000   

           ...               X170          X171          X172          X173  \
count      ...       11500.000000  11500.000000  11500.000000  11500.000000   
mean       ...         -10.145739    -11.630348    -12.943478    -13.668870   
std        ...         164.652883    166.149790    168.554058    168.556486   
min        ...       -1867.000000  -1865.000000  -1642.000000  -1723.000000   
25%        ...         -55.000000    -56.000000    -56.000000    -56.000000   
50%        ...          -9.000000    -10.000000    -10.000000    -10.000000   
75%        ...          34.000000     34.000000     33.000000     33.000000   
max        ...        1777.000000   1472.000000   1319.000000   1436.000000   

               X174          X175          X176          X177          X178  \
count  11500.000000  11500.000000  11500.000000  11500.000000  11500.000000   
mean     -13.363304    -13.045043    -12.705130    -12.426000    -12.195652   
std      167.257290    164.241019    162.895832    162.886311    164.852015   
min    -1866.000000  -1863.000000  -1781.000000  -1727.000000  -1829.000000   
25%      -55.000000    -56.000000    -55.000000    -55.000000    -55.000000   
50%      -10.000000     -9.000000     -9.000000     -9.000000     -9.000000   
75%       34.000000     34.000000     34.000000     34.000000     34.000000   
max     1733.000000   1958.000000   2047.000000   2047.000000   1915.000000   

                  y  
count  11500.000000  
mean       3.000000  
std        1.414275  
min        1.000000  
25%        2.000000  
50%        3.000000  
75%        4.000000  
max        5.000000  

[8 rows x 179 columns]

In [89]:
df.isnull().values.any()

False

In [206]:
df.corr()

X1        X2        X3        X4        X5        X6        X7  \
X1    1.000000  0.947729  0.808192  0.608109  0.393674  0.218226  0.103693   
X2    0.947729  1.000000  0.944623  0.790403  0.576579  0.369803  0.211793   
X3    0.808192  0.944623  1.000000  0.939522  0.778648  0.573874  0.382493   
X4    0.608109  0.790403  0.939522  1.000000  0.938636  0.784954  0.590497   
X5    0.393674  0.576579  0.778648  0.938636  1.000000  0.941267  0.792304   
X6    0.218226  0.369803  0.573874  0.784954  0.941267  1.000000  0.942732   
X7    0.103693  0.211793  0.382493  0.590497  0.792304  0.942732  1.000000   
X8    0.044483  0.109478  0.231084  0.399855  0.596424  0.794265  0.943499   
X9    0.027923  0.060218  0.133249  0.250052  0.410651  0.607889  0.804300   
X10   0.032221  0.043565  0.080003  0.150284  0.265112  0.429895  0.624709   
X11   0.040119  0.042230  0.054331  0.088767  0.159434  0.277652  0.437747   
X12   0.035647  0.038162  0.041668  0.056826  0.095688  0.169070  0.279857   
X13   0.009950  0.019416  0.026530  0.035834  0.056095  0.093783  0.157256   
X14  -0.027824 -0.007544  0.011323  0.025675  0.039551  0.054374  0.081917   
X15  -0.067519 -0.037875 -0.008082  0.013586  0.027529  0.030556  0.036624   
X16  -0.103498 -0.068782 -0.033320 -0.006570  0.010352  0.011666  0.009956   
X17  -0.129956 -0.098616 -0.065669 -0.038564 -0.018654 -0.010731 -0.006062   
X18  -0.140550 -0.121110 -0.100113 -0.078758 -0.056762 -0.036902 -0.015078   
X19  -0.136456 -0.133449 -0.128104 -0.115846 -0.093578 -0.061655 -0.021296   
X20  -0.116471 -0.129880 -0.140955 -0.140112 -0.122881 -0.086455 -0.036619   
X21  -0.089462 -0.115972 -0.140121 -0.150236 -0.141336 -0.108688 -0.059218   
X22  -0.059348 -0.092897 -0.125213 -0.144151 -0.145120 -0.122864 -0.084065   
X23  -0.032130 -0.066815 -0.102256 -0.127593 -0.137250 -0.126666 -0.101274   
X24  -0.003778 -0.035261 -0.070201 -0.099149 -0.115678 -0.115390 -0.102529   
X25   0.022393 -0.002148 -0.034079 -0.063818 -0.084971 -0.093729 -0.092284   
X26   0.045038  0.028793  0.001818 -0.026676 -0.049625 -0.064293 -0.072471   
X27   0.065780  0.058568  0.036775  0.008765 -0.017431 -0.038002 -0.053866   
X28   0.085341  0.087011  0.069815  0.041272  0.009565 -0.018048 -0.040621   
X29   0.106417  0.114048  0.099279  0.068918  0.032158 -0.001844 -0.029508   
X30   0.122688  0.134293  0.122287  0.093305  0.054791  0.017488 -0.014071   
...        ...       ...       ...       ...       ...       ...       ...   
X150 -0.017294 -0.022812 -0.018978 -0.004617  0.011758  0.020916  0.020464   
X151 -0.012058 -0.010965 -0.006283  0.002981  0.008686  0.007462 -0.000061   
X152 -0.000565  0.004039  0.007655  0.010816  0.005648 -0.005421 -0.018240   
X153  0.006657  0.011242  0.011787  0.010145 -0.001906 -0.017806 -0.031366   
X154  0.009527  0.009383  0.005419  0.001175 -0.010346 -0.023626 -0.032842   
X155  0.008568  0.002718 -0.005595 -0.010911 -0.017291 -0.023258 -0.025546   
X156  0.008700 -0.001754 -0.011756 -0.015031 -0.013783 -0.010770 -0.007370   
X157  0.009040 -0.001144 -0.007375 -0.004415  0.006026  0.016935  0.022242   
X158  0.008410  0.003471  0.005107  0.015828  0.032969  0.048284  0.051196   
X159  0.005102  0.007744  0.019473  0.037829  0.058617  0.073547  0.071031   
X160  0.006229  0.014644  0.031805  0.051925  0.070090  0.079919  0.072940   
X161  0.011509  0.024538  0.041972  0.057874  0.068585  0.070282  0.060823   
X162  0.015700  0.031304  0.046523  0.056084  0.057936  0.052658  0.043283   
X163  0.017597  0.031087  0.041307  0.045401  0.041022  0.033024  0.027412   
X164  0.009821  0.019802  0.027028  0.030520  0.027196  0.022325  0.023240   
X165  0.001099  0.008815  0.013457  0.017490  0.018370  0.019935  0.027213   
X166 -0.008779 -0.002849  0.001705  0.008320  0.015977  0.025626  0.039432   
X167 -0.013999 -0.008964 -0.002471  0.006527  0.019567  0.033796  0.050173   
X168 -0.009253 -0.008387 -0.003512  0.004060  0.018416  0.034720  0.052064   
X169  0.006206 -0.001270 -0.002198

From the analysis we know that the data
RangeIndex: 11500 entries
dtypes: int64(179), object(1)
NA values : zero
Column 'Unnamed: 0' is object

# Preprocessing 

In [90]:
#Dropping the 'Unnamed: 0' column
df.drop('Unnamed: 0',inplace=True,axis=1)

In [91]:
df.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10 ...  X170  X171  X172  \
0  135  190  229  223  192  125   55   -9  -33  -38 ...   -17   -15   -31   
1  386  382  356  331  320  315  307  272  244  232 ...   164   150   146   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94 ...    57    64    48   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79 ...   -82   -81   -80   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59 ...     4     2   -12   

   X173  X174  X175  X176  X177  X178  y  
0   -77  -103  -127  -116   -83   -51  4  
1   152   157   156   154   143   129  1  
2    19   -12   -30   -35   -35   -36  5  
3   -77   -85   -77   -72   -69   -65  5  
4   -32   -41   -65   -83   -89   -73  5  

[5 rows x 179 columns]

In [92]:
#target variable
#df['y'] = df['y'].apply(lambda x: 1 if x == 1 else 0)
y=df['y']


In [93]:
y = y.apply(lambda x: 1 if x == 1 else 0)
y.unique()


array([0, 1], dtype=int64)

In [94]:
#dropping the y column
X=df.drop('y',axis=1)
X.head()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...   X169  X170  X171  \
0  135  190  229  223  192  125   55   -9  -33  -38  ...      8   -17   -15   
1  386  382  356  331  320  315  307  272  244  232  ...    168   164   150   
2  -32  -39  -47  -37  -32  -36  -57  -73  -85  -94  ...     29    57    64   
3 -105 -101  -96  -92  -89  -95 -102 -100  -87  -79  ...    -80   -82   -81   
4   -9  -65  -98 -102  -78  -48  -16    0  -21  -59  ...     10     4     2   

   X172  X173  X174  X175  X176  X177  X178  
0   -31   -77  -103  -127  -116   -83   -51  
1   146   152   157   156   154   143   129  
2    48    19   -12   -30   -35   -35   -36  
3   -80   -77   -85   -77   -72   -69   -65  
4   -12   -32   -41   -65   -83   -89   -73  

[5 rows x 178 columns]

In [95]:
#SCALING
from sklearn.preprocessing import StandardScaler
scale=StandardScaler().fit(X)
x_scaled=scale.transform(X)
x_scaled

array([[ 0.88505134,  1.20992878,  1.46276429, ..., -0.63414367,
        -0.43329036, -0.23539922],
       [ 2.40057718,  2.36619038,  2.23944096, ...,  1.02342937,
         0.95424076,  0.85653664],
       [-0.12328657, -0.16915405, -0.22513147, ..., -0.13687176,
        -0.13859348, -0.14440456],
       ...,
       [ 0.1544592 ,  0.10184476, -0.01720228, ...,  0.0657205 ,
         0.07015014,  0.02545213],
       [-0.17159018, -0.08484331,  0.00725997, ...,  0.49546166,
         0.43852123,  0.40762968],
       [ 0.24502848,  0.31262161,  0.41088722, ...,  0.0657205 ,
         0.08856869,  0.19530882]])

# Dimensionality Reduction

As the data has the High number of variables 

Using principal component analysis we are reducing the dimension of the data

In [150]:
#PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=2)  #two component
principalComponents = pca.fit_transform(x_scaled)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [151]:
principalDf.head()

principal component 1  principal component 2
0              -0.072038              -1.277543
1              -1.382837              -4.178983
2               0.481301              -0.234837
3              -0.198281               0.283747
4              -0.258733               0.172941

In [152]:
#Concating Principal components and y varaible
PCAdf= pd.concat([principalDf, y], axis = 1)
PCAdf.head()


principal component 1  principal component 2  y
0              -0.072038              -1.277543  0
1              -1.382837              -4.178983  1
2               0.481301              -0.234837  0
3              -0.198281               0.283747  0
4              -0.258733               0.172941  0

In [153]:
PCAdf.shape

(11500, 3)

# T-SNE

T-sne is an another dimensionality reduction techinique 

This algorithm reduces the variables into two components

In [100]:
from sklearn.manifold import TSNE

TNSEdf = TSNE(random_state=r_s).fit_transform(x_scaled)
TNSEdf.shape

(11500, 2)

In [104]:
tnsedf = pd.DataFrame(TNSEdf)

In [106]:
tnsedf['y']=y

In [107]:
tnsedf.head()

0          1  y
0  11.993948  24.872997  0
1  -7.594337 -50.572933  1
2  32.541359 -16.339283  0
3  44.624897 -35.663342  0
4  -6.123447  -9.328798  0

# K-MEANS

We use k-Means clustering algorithm for clustering  pca and T-sne components

In [112]:
#K-Means
from sklearn.cluster import KMeans

# Number of clusters
kmeans = KMeans(n_clusters=5)

# Centroid values
#centroids = kmeans.cluster_centers_

# Implementing kmeans in pca

In [124]:
#implementing kmeans in pcadf
kmeansPCA = kmeans.fit(principalDf)
#Getting the cluster labels
labels = kmeans.predict(principalDf)

In [135]:
PK_df= PCAdf

In [136]:
PK_df['kclust']=labels

In [138]:
PK_df['kclust'].unique()

array([0, 4, 2, 1, 3], dtype=int64)

# implementing kmeans in T-SNE

In [140]:
#K-Means
from sklearn.cluster import KMeans
# Number of clusters
kmeans = KMeans(n_clusters=5)
#implementing kmeans in tnsedf
kmeanstnse = kmeans.fit(TNSEdf)
#Getting the cluster labels
k_labels = kmeans.predict(TNSEdf)

In [141]:
TK_df = tnsedf

In [142]:
TK_df['cluster']=k_labels

In [143]:
TK_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 4 columns):
0          11500 non-null float32
1          11500 non-null float32
y          11500 non-null int64
cluster    11500 non-null int32
dtypes: float32(2), int32(1), int64(1)
memory usage: 224.7 KB


In [145]:
TK_df['cluster'].unique()

array([2, 4, 0, 1, 3], dtype=int64)

So, now we have four dataframes,

1.PCAdf    => PCA only.

2.tnsedf   => T-SNE only.

3.PK_df    => PCA + KMeans.

4.TK_df    => T-SNE + Kmeans

but for simplicity only two dataframes are used to compare the accuracies

# Splitting the data into train and test

In [167]:
#splitting into x and y varialbles
'''
p_x=PCAdf.loc[:,['principal component 1','principal component 2']]
p_y=PCAdf ['y']

t_x=tnsedf.loc[:,[0,1]]
t_y=tnsedf['y']
'''

pk_x=PK_df.loc[:,['principal component 1','principal component 2','kclust']]
pk_y=PK_df['y']

tk_x=TK_df.loc[:,[0,1,'cluster']]
tk_y=TK_df['y']

In [168]:
from sklearn.model_selection import train_test_split
'''
#only PCA
px_train, px_test, py_train, py_test = train_test_split(p_x,p_y,
                                                    test_size = 0.2, 
                                                    random_state = 101)'''

#PCA +k-means
pkx_train, pkx_test, pky_train, pky_test = train_test_split(pk_x,pk_y,
                                                            test_size = 0.2, 
                                                            random_state = 101)

'''
#T-sne only
tx_train, tx_test, ty_train, ty_test = train_test_split(t_x,t_y,
                                                        test_size = 0.2, 
                                                        random_state = 101)'''

#T-SNE + k-means
tkx_train, tkx_test, tky_train, tky_test = train_test_split(tk_x,tk_y,
                                                            test_size = 0.2, 
                                                            random_state = 101)

# Metrics for Classification

In [180]:
#Confusion matrix and accuraccy score
from sklearn.metrics import confusion_matrix, accuracy_score
#Cross validation
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

There are several metrics can be used to tell how good the model performance is.(EX: ROC,AUC,SENSIVITY,MISCLASSIFICATION ERROR,R^2,ADJ R^2,ETC.,.)

But here we take only confusion matrix and Accuracy score.


# Logistic regression

In [170]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression() 

logmodel.fit(pkx_train,pky_train)
pklogpred = logmodel.predict(pkx_test)


logmodel.fit(tkx_train,tky_train)
tklogpred = logmodel.predict(tkx_test)

In [181]:
print(confusion_matrix(pky_test, pklogpred))
print(round(accuracy_score(pky_test, pklogpred),2)*100)

[[1866    0]
 [ 241  193]]
90.0


In [182]:
print(confusion_matrix(tky_test, tklogpred))
print(round(accuracy_score(tky_test, tklogpred),2)*100)

[[1807   59]
 [ 262  172]]
86.0


log(PCA + K-Means) gives the higher accuracy of 90.0

In [195]:
#cross validation
LOGCV = (cross_val_score(logmodel, tkx_train, tky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

# KNN

In [173]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(pkx_train, pky_train)
pknnpred = knn.predict(pkx_test)

knn.fit(tkx_train,tky_train)
tknnpred = knn.predict(tkx_test)


In [183]:
print(confusion_matrix(pky_test, pknnpred))
print(round(accuracy_score(pky_test, pknnpred),2)*100)

[[1809   57]
 [  98  336]]
93.0


In [184]:
print(confusion_matrix(tky_test, tknnpred))
print(round(accuracy_score(tky_test, tknnpred),2)*100)

[[1834   32]
 [  95  339]]
94.0


KNN(T-sne + k-means) gives the higher accuracy of 94.0

In [196]:
KNNCV = (cross_val_score(knn, tkx_train, tky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

# SVM

In [174]:
from sklearn.svm import SVC
svc= SVC(kernel = 'sigmoid')
#There are various kernels linear,rbf
svc.fit(pkx_train, pky_train)
pspred = svc.predict(pkx_test)

svc.fit(tkx_train, tky_train)
tspred = svc.predict(tkx_test)


In [185]:

print(confusion_matrix(pky_test, pspred))
print(round(accuracy_score(pky_test, pspred),2)*100)

[[1529  337]
 [ 297  137]]
72.0


In [186]:
print(confusion_matrix(tky_test, tspred))
print(round(accuracy_score(tky_test, tspred),2)*100)

[[1383  483]
 [ 395   39]]
62.0


SVM(PCA + k-means) gives the accuracy of 72.0

In [202]:
SVCCV = (cross_val_score(svc, pkx_train, pky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

# Random forest

In [175]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 200)#criterion = entopy,gini

rfc.fit(pkx_train, pky_train)
prpred = rfc.predict(pkx_test)

rfc.fit(tkx_train, tky_train)
trpred = rfc.predict(tkx_test)


In [187]:
print(confusion_matrix(pky_test, prpred))
print(round(accuracy_score(pky_test, prpred),2)*100)

[[1806   60]
 [  96  338]]
93.0


In [188]:
print(confusion_matrix(tky_test, trpred))
print(round(accuracy_score(tky_test, trpred),2)*100)

[[1846   20]
 [  81  353]]
96.0


RF(T-sne + k-Means) gives the higher accuracy of  96.0

In [197]:
#Cross validation
RFCCV = (cross_val_score(rfc, tkx_train, tky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

# Naive Bayes

In [176]:
from sklearn.naive_bayes import GaussianNB
gaussiannb= GaussianNB()

gaussiannb.fit(pkx_train, pky_train)
pgpred = gaussiannb.predict(pkx_test)

gaussiannb.fit(tkx_train, tky_train)
tgpred = gaussiannb.predict(tkx_test)

In [189]:
print(confusion_matrix(pky_test, pgpred))
print(round(accuracy_score(pky_test, pgpred),2)*100)

[[1850   16]
 [ 130  304]]
94.0


In [198]:
print(confusion_matrix(tky_test, tgpred))
print(round(accuracy_score(tky_test, tgpred),2)*100)

[[1839   27]
 [ 289  145]]
86.0


NB(PCA + k-means) gives as higher accuracy of 94.0

In [199]:
NBCV = (cross_val_score(gaussiannb, pkx_train, pky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

# XGboost

In [177]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
xgb = XGBClassifier()

xgb.fit(pkx_train, pky_train)
pxpred = xgb.predict(pkx_test)

xgb.fit(tkx_train, tky_train)
txpred = xgb.predict(tkx_test)

C:\Users\priyasathya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\priyasathya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [191]:
print(confusion_matrix(pky_test, pxpred))
print(round(accuracy_score(pky_test, pxpred),2)*100)

[[1833   33]
 [  92  342]]
95.0


In [194]:
print(confusion_matrix(tky_test, txpred))
print(round(accuracy_score(tky_test, txpred),2)*100)

[[1817   49]
 [ 117  317]]
93.0


XG(T-sne + k-means) gives as higher accuracy of 95.0

In [200]:
XGCV = (cross_val_score(xgb, pkx_train, pky_train, cv=k_fold, n_jobs=1, scoring = 'accuracy').mean())

C:\Users\priyasathya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\priyasathya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\priyasathya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\priyasathya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous

# Performance comparison

In [203]:
models = pd.DataFrame({
                'Models': ['Random Forest Classifier', 'Support Vector Machine',
                           'K-Near Neighbors', 'Logistic Model', 'Gausian NB', 'XGBoost'],
                'Score':  [RFCCV, SVCCV, KNNCV, LOGCV, NBCV, XGCV]})

models.sort_values(by='Score', ascending=False)

Models     Score
0  Random Forest Classifier  0.949783
5                   XGBoost  0.941630
2          K-Near Neighbors  0.936304
4                Gausian NB  0.933043
3            Logistic Model  0.858043
1    Support Vector Machine  0.718152

From the above cross validation scores we get that random forest gives the high performance for this dataset.

This is only the conlusion for the models built here , still the performance can be increased by adjusting the parameters.